<?php
return array(
'sitename'=> '新灵旅行',
'shortTitle'=> '带上新的生活去旅行',
'domain'=> 'http://www.newsoul.cn',
'address'=> '重庆市江北观音桥',
'phone'=> '023-12345678',
'email'=> 'admin@admin.com',
'beian'=> '渝备12345678',
'copyright'=> '2012-2013',
'baseurl'=> 'http://localhost/acopy/',
'userDefaultGroup'=> '5',
'closeSite'=> '1',
'mobile'=> '1',
'attachDir'=> 'http://localhost/acopy/attachments/',
'service_aim_cn'=> '致力于提升客户品牌形象、实现客户商业目标!',
'service_aim_en'=> 'Commitment to enhance customer brand image,customer business goals!',
'imgUploadNum'=> '1',
'imgMinWidth'=> '300',
'imgMinHeight'=> '300',
'imgAllowTypes'=> '*.jpg;*.png;*.jpeg',
'imgThumbSize'=> '124,200,300,600,origin',
'imgMaxSize'=> '1024000',
'imgQuality'=> '80',
'logo'=> 'common/images/logo.png',
'perPageNum'=> '10',
'readLocalDir'=> 'D:\\AppServ\\www\\acopy\\protected/../attachments/',
'readAttachDir'=> 'http://localhost/acopy/attachments/',
'downloadLocalDir'=> 'D:\\\\\\\\AppServ\\\\\\\\www\\\\\\\\acopy\\\\\\\\protected/../attachments/',
'downloadAttachDir'=> 'http://localhost/acopy/attachments/',
'readLocalFiles'=> '*.html;*.htm;*.exe',
);
?>