<?php
return array(
'sitename'=> '新灵旅行',
'shortTitle'=> '带上新的生活去旅行',
'domain'=> 'http://www.newsoul.cn',
'address'=> '重庆市江北观音桥',
'phone'=> '023-12345678',
'email'=> 'admin@admin.com',
'beian'=> '渝备12345678',
'copyright'=> '2012-2013',
'baseurl'=> 'http://localhost/wifi/',
'version'=> 'Alpha 1.0',
'imgUploadNum'=> '1',
'imgMinWidth'=> '300',
'imgMinHeight'=> '300',
'imgAllowTypes'=> '*.jpg;*.png;*.jpeg',
'imgThumbSize'=> '124,200,300,600,origin',
'imgMaxSize'=> '1024000',
'imgQuality'=> '80',
'closeSite'=> '1',
'mobile'=> '1',
'userDefaultGroup'=> '5',
'attachDir'=> 'http://localhost/acopy/attachments/',
'service_aim_cn'=> '致力于提升客户品牌形象、实现客户商业目标!',
'service_aim_en'=> 'Commitment to enhance customer brand image,customer business goals!',
'perPageNum'=> '10',
'logo'=> 'common/images/logo.png',
'closeSiteReason'=> '系统正在维护中，请稍后再访问！',
'readLocalDir'=> 'C:\\AppServ\\www\\wifi\\protected/../attachments/',
'downloadLocalDir'=> 'C:\\AppServ\\www\\wifi\\protected/../attachments/',
'shopGroupId'=> '5',
'noticeall'=> '近期收到举报，有部分网站有不良信息，望各位店家及时处理！',
'forbidnotshop'=> '1',
'validateEmail'=> '0',
'adminGroupIds'=> 'Array',
);
?>